spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reportdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
plan-api:
  messages:
    planSaveSucc: Plan Saved Successfully
    planSaveFail: Plan Save Failed
server:
  forward-headers-strategy: framework
